"""added_invitations

Revision ID: 0aa1ff595a9f
Revises: e17e81ece7e2
Create Date: 2020-05-16 23:35:30.026999

"""

# revision identifiers, used by Alembic.
revision = '0aa1ff595a9f'
down_revision = 'e17e81ece7e2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('invitation_key', sa.String(length=100), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('role_code', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user_user.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_invitation')
    ### end Alembic commands ###
