"""Working on gateway relationships, allowing incoming and outgoing gateways

Revision ID: 114f20c16421
Revises: 539ec9a1bc41
Create Date: 2014-04-26 12:17:29.014026

"""

# revision identifiers, used by Alembic.
revision = '114f20c16421'
down_revision = '539ec9a1bc41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'telephony_gateway', sa.Column('extra_string', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'telephony_gateway', 'extra_string')
    ### end Alembic commands ###
