"""telephony_created_at

Revision ID: 13b2e84fd798
Revises: 1cb4253a8bc6
Create Date: 2014-04-27 19:21:15.493456

"""

# revision identifiers, used by Alembic.
revision = '13b2e84fd798'
down_revision = '1cb4253a8bc6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import datetime

def upgrade():
    table_names = [ 'telephony_call',
                    'telephony_gateway',
                    'telephony_message',
                    'telephony_phonenumber']

    #first create columns with nullable=True
    for table_name in table_names:
        op.add_column(table_name, sa.Column('created_at', type_=sa.DateTime(timezone=True), nullable=True))
        op.add_column(table_name, sa.Column('updated_at', type_=sa.DateTime(timezone=True), nullable=True))

    #then set times to now
    for table_name in table_names:
        created_at = sa.sql.table(table_name, sa.sql.column('created_at'))
        op.execute(created_at.update().values(created_at=datetime.datetime.now()))

        updated_at = sa.sql.table(table_name, sa.sql.column('updated_at'))
        op.execute(updated_at.update().values(updated_at=datetime.datetime.now()))

    #then set back to nullable=False
    for table_name in table_names:
        op.alter_column(table_name, 'created_at', nullable=False)
        op.alter_column(table_name, 'updated_at', nullable=False)



def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'telephony_phonenumber', 'updated_at')
    op.drop_column(u'telephony_phonenumber', 'created_at')
    op.drop_column(u'telephony_message', 'updated_at')
    op.drop_column(u'telephony_message', 'created_at')
    op.drop_column(u'telephony_gateway', 'updated_at')
    op.drop_column(u'telephony_gateway', 'created_at')
    op.drop_column(u'telephony_call', 'updated_at')
    op.drop_column(u'telephony_call', 'created_at')
    ### end Alembic commands ###
