"""add_order_uploads

Revision ID: 14665e1003a2
Revises: 2a96ee2970e3
Create Date: 2016-09-15 14:19:00.223008

"""

# revision identifiers, used by Alembic.
revision = '14665e1003a2'
down_revision = '2a96ee2970e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_uploads', sa.Column('order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_uploads', 'order')
    ### end Alembic commands ###
