"""gw_sharable

Revision ID: 1508a1f7cc1c
Revises: 4c20ef57d701
Create Date: 2019-05-09 16:31:03.943000

"""

# revision identifiers, used by Alembic.
revision = '1508a1f7cc1c'
down_revision = '4c20ef57d701'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_content_type')
    op.add_column('onair_program', sa.Column('episode_id', sa.Integer(), nullable=True))
    op.add_column('onair_program', sa.Column('scheduledprogram_id', sa.Integer(), nullable=True))
    op.drop_column('onair_program', 'scheduledepisode_id')
    op.add_column('telephony_gateway', sa.Column('sharable', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telephony_gateway', 'sharable')
    op.add_column('onair_program', sa.Column('scheduledepisode_id', sa.INTEGER(), nullable=True))
    op.drop_column('onair_program', 'scheduledprogram_id')
    op.drop_column('onair_program', 'episode_id')
    op.create_table('radio_content_type',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default="nextval('radio_content_type_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'radio_content_type_pkey')
    )
    ### end Alembic commands ###
