"""rerun station gateway

Revision ID: 17b858dd8d3d
Revises: 4d0be367f095
Create Date: 2014-04-26 14:04:22.078545

"""

# revision identifiers, used by Alembic.
revision = '17b858dd8d3d'
down_revision = '4d0be367f095'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'telephony_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_top', sa.Integer(), nullable=True),
    sa.Column('number_bottom', sa.Integer(), nullable=True),
    sa.Column('sofia_string', sa.String(length=160), nullable=True),
    sa.Column('extra_string', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'radio_station', sa.Column('gateway_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'radio_station', 'gateway_id')
    op.drop_table(u'telephony_gateway')
    ### end Alembic commands ###
