"""added_netwk_person

Revision ID: 18c638d45ed2
Revises: 2d17846830ad
Create Date: 2016-11-15 15:54:19.958073

"""

# revision identifiers, used by Alembic.
revision = '18c638d45ed2'
down_revision = '2d17846830ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_person', sa.Column('network_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_person', 'network_id')
    ### end Alembic commands ###
