"""make networks mandatory for stns

Revision ID: 18e187ffe893
Revises: 571474b47435
Create Date: 2016-09-23 06:10:14.630389

"""

# revision identifiers, used by Alembic.
revision = '18e187ffe893'
down_revision = '571474b47435'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', 'network_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', 'network_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
