"""stn_vol_flt_int

Revision ID: 1a24e052e5be
Revises: 50b58d5a1a3c
Create Date: 2018-12-29 18:34:12.593560

"""

# revision identifiers, used by Alembic.
revision = '1a24e052e5be'
down_revision = '50b58d5a1a3c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', 'audio_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', 'audio_volume',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
   
    ### end Alembic commands ###
