"""stn_vol_flt_int

Revision ID: 1a24e052e5be
Revises: 50b58d5a1a3c
Create Date: 2018-12-29 18:34:12.593560

"""

# revision identifiers, used by Alembic.
revision = '1a24e052e5be'
down_revision = '50b58d5a1a3c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_content_type')
    op.add_column('onair_program', sa.Column('episode_id', sa.Integer(), nullable=True))
    op.add_column('onair_program', sa.Column('scheduledprogram_id', sa.Integer(), nullable=True))
    op.drop_column('onair_program', 'scheduledepisode_id')
    op.alter_column('radio_station', 'audio_volume',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', 'audio_volume',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('onair_program', sa.Column('scheduledepisode_id', sa.INTEGER(), nullable=True))
    op.drop_column('onair_program', 'scheduledprogram_id')
    op.drop_column('onair_program', 'episode_id')
    op.create_table('radio_content_type',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default="nextval('radio_content_type_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'radio_content_type_pkey')
    )
    ### end Alembic commands ###
