"""voice_prompt_default_deleted_field

Revision ID: 1ae1c8228945
Revises: 4308b0b7701f
Create Date: 2019-09-03 13:24:17.497818

"""

# revision identifiers, used by Alembic.
revision = '1ae1c8228945'
down_revision = '4308b0b7701f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
