"""duration_to_interval

Revision ID: 1ba2e0725603
Revises: 27fab241689c
Create Date: 2014-03-12 16:53:23.447958

"""

# revision identifiers, used by Alembic.
revision = '1ba2e0725603'
down_revision = '27fab241689c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    #convert time column to interval, so create native timedelta
    op.alter_column('radio_program', 'duration',
               existing_type=sa.TIME(),
               type_=sa.types.Interval(),
               nullable=False)

    #cleanup misc
    ### commands auto generated by Alembic ###
    op.drop_column(u'radio_location', u'modifieddate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic ###
    op.add_column(u'radio_location', sa.Column(u'modifieddate', sa.DATE(), nullable=True))
    ### end Alembic commands ###
