"""Add last time of access for station

Revision ID: 1f9eed32fdc0
Revises: 2970098205c8
Create Date: 2018-10-05 12:23:34.060160

"""

# revision identifiers, used by Alembic.
revision = '1f9eed32fdc0'
down_revision = '2970098205c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('last_accessed_mobile', sa.DateTime(timezone=False), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'last_accessed_mobile')
    ### end Alembic commands ###
