"""Delete community menus

Revision ID: 20bf500febc8
Revises: 261df279c2c1
Create Date: 2019-07-19 12:03:28.183940

"""

# revision identifiers, used by Alembic.
revision = '20bf500febc8'
down_revision = '261df279c2c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_communitymenu', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_communitymenu', 'deleted')
    ### end Alembic commands ###
