"""add_datecr_podcast

Revision ID: 21af3957d566
Revises: 40814799d18d
Create Date: 2016-11-14 19:37:02.925777

"""

# revision identifiers, used by Alembic.
revision = '21af3957d566'
down_revision = '40814799d18d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_podcastdownload', 'date_created')
    ### end Alembic commands ###
