"""add_deflt_dlt_pllstitm

Revision ID: 21c434fca60d
Revises: 52c5abfc6ff8
Create Date: 2016-11-29 18:56:14.715618

"""

# revision identifiers, used by Alembic.
revision = '21c434fca60d'
down_revision = '52c5abfc6ff8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylistitem', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_musicplaylistitem', 'deleted')
    ### end Alembic commands ###
