"""podcast_descr_totxt

Revision ID: 22cc5d6d7fc0
Revises: 21af3957d566
Create Date: 2016-11-14 20:18:46.473803

"""

# revision identifiers, used by Alembic.
revision = '22cc5d6d7fc0'
down_revision = '21af3957d566'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
