"""multicast_port

Revision ID: 23999ea09423
Revises: 37b19b31785d
Create Date: 2016-08-23 10:40:23.765422

"""

# revision identifiers, used by Alembic.
revision = '23999ea09423'
down_revision = '37b19b31785d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('broadcast_port', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'broadcast_port')
    ### end Alembic commands ###
