"""add approval to community content

Revision ID: 2413c9f0671f
Revises: 1508a1f7cc1c
Create Date: 2019-05-14 14:26:19.936313

"""

# revision identifiers, used by Alembic.
revision = '2413c9f0671f'
down_revision = '1508a1f7cc1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_communitycontent', sa.Column('approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_communitycontent', 'approved')
    ### end Alembic commands ###
