"""add series id for recurring events

Revision ID: 25b2974c7078
Revises: 2150eb3e6577
Create Date: 2019-02-15 03:55:14.353373

"""

# revision identifiers, used by Alembic.
revision = '25b2974c7078'
down_revision = '2150eb3e6577'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_scheduledprogram', sa.Column('series_id', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_scheduledprogram', 'series_id')
    ### end Alembic commands ###
