"""fase2_uploads

Revision ID: 25c0610f6dbf
Revises: 54d62f4942f6
Create Date: 2016-09-01 16:58:19.619571

"""

# revision identifiers, used by Alembic.
revision = '25c0610f6dbf'
down_revision = '54d62f4942f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_track', sa.Column('content_contenttypeid', sa.Integer(), nullable=True))
    op.add_column(u'content_track', sa.Column('description', sa.Text(), nullable=True))
    op.add_column(u'content_track', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column(u'content_track', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column(u'content_track', sa.Column('uri', sa.String(length=200), nullable=True))
    op.add_column(u'content_uploads', sa.Column('contenttrack_id', sa.Integer(), nullable=True))
    op.add_column(u'content_uploads', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column(u'content_uploads', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    op.add_column(u'content_uploads', sa.Column('uri', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_uploads', 'uri')
    op.drop_column(u'content_uploads', 'uploaded_by')
    op.drop_column(u'content_uploads', 'name')
    op.drop_column(u'content_uploads', 'contenttrack_id')
    op.drop_column(u'content_track', 'uri')
    op.drop_column(u'content_track', 'uploaded_by')
    op.drop_column(u'content_track', 'name')
    op.drop_column(u'content_track', 'description')
    op.drop_column(u'content_track', 'content_contenttypeid')
    ### end Alembic commands ###
