"""Delete voice prompts

Revision ID: 261df279c2c1
Revises: 591720fcad12
Create Date: 2019-07-19 11:58:11.563391

"""

# revision identifiers, used by Alembic.
revision = '261df279c2c1'
down_revision = '591720fcad12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_voiceprompt', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration_voiceprompt', 'deleted')
    ### end Alembic commands ###
