"""change status in scheduledProgram

Revision ID: 266aacbd242e
Revises: 0937f7e9feb5
Create Date: 2019-09-18 21:53:35.193495

"""

# revision identifiers, used by Alembic.
revision = '266aacbd242e'
down_revision = '0937f7e9feb5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'configuration_voiceprompt', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_communitycontent', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_communitymenu', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_music', 'content_musicalbum', ['album_id'], ['id'])
    op.create_foreign_key(None, 'content_music', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_music', 'content_musicartist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'content_music_musicartist', 'content_music', ['music_id'], ['id'])
    op.create_foreign_key(None, 'content_music_musicartist', 'content_musicartist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'content_musicalbum', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_musicartist', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_musicplaylist', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'content_musicplaylistitem', 'content_musicplaylist', ['playlist_id'], ['id'])
    op.create_foreign_key(None, 'content_musicplaylistitem', 'content_musicplaylistitemtype', ['playlist_item_type_id'], ['id'])
    op.create_foreign_key(None, 'content_podcastdownload', 'content_podcast', ['podcast_id'], ['id'])
    op.create_foreign_key(None, 'content_track', 'content_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'content_tracknetwork', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'content_tracknetwork', 'content_track', ['track_id'], ['id'])
    op.create_foreign_key(None, 'content_uploads', 'content_track', ['track_id'], ['id'])
    op.create_foreign_key(None, 'content_uploads', 'content_type', ['type_id'], ['id'])
    op.create_foreign_key(None, 'onair_program', 'radio_scheduledprogram', ['scheduledprogram_id'], ['id'])
    op.create_foreign_key(None, 'radio_episode', 'radio_program', ['program_id'], ['id'])
    op.create_foreign_key(None, 'radio_incominggateway', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_networkpadding', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_networkusers', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_outgoinggateway', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_person', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_personlanguage', 'radio_person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'radio_personlanguage', 'radio_language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'radio_personnetwork', 'radio_person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'radio_personnetwork', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_program', 'radio_programtype', ['program_type_id'], ['id'])
    op.create_foreign_key(None, 'radio_program', 'radio_language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'radio_programnetwork', 'radio_program', ['program_id'], ['id'])
    op.create_foreign_key(None, 'radio_programnetwork', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_role', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_role', 'radio_person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'radio_scheduledblock', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_scheduledprogram', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_scheduledprogram', 'radio_program', ['program_id'], ['id'])
    op.alter_column('radio_station', 'last_accessed_mobile',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'radio_station', ['api_key'])
    op.create_foreign_key(None, 'radio_station', 'radio_network', ['network_id'], ['id'])
    op.create_foreign_key(None, 'radio_station', 'radio_ttsvoice', ['tts_voice_id'], ['id'])
    op.create_foreign_key(None, 'radio_station', 'radio_ttssamplerate', ['tts_samplerate_id'], ['id'])
    op.create_foreign_key(None, 'radio_station', 'radio_location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'radio_station', 'radio_ttsaudioformat', ['tts_audioformat_id'], ['id'])
    op.create_foreign_key(None, 'radio_stationanalytic', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_stationevent', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_stationlanguage', 'radio_language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'radio_stationlanguage', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'radio_ttsvoice', 'radio_language', ['language_id'], ['id'])
    op.create_foreign_key(None, 'radio_whitelist', 'radio_station', ['station_id'], ['id'])
    op.drop_constraint(u'telephony_call_onairprogram_id_fkey', 'telephony_call', type_='foreignkey')
    op.create_foreign_key(None, 'telephony_call', 'radio_station', ['station_id'], ['id'])
    op.create_foreign_key(None, 'telephony_call', 'radio_program', ['onairprogram_id'], ['id'])
    op.create_foreign_key(None, 'telephony_message', 'radio_station', ['station_id'], ['id'])

    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='status::integer')
    ### end Alembic commands ###


def downgrade():

    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telephony_message', type_='foreignkey')
    op.drop_constraint(None, 'telephony_call', type_='foreignkey')
    op.drop_constraint(None, 'telephony_call', type_='foreignkey')
    op.create_foreign_key(u'telephony_call_onairprogram_id_fkey', 'telephony_call', 'onair_program', ['onairprogram_id'], ['id'])
    op.drop_constraint(None, 'radio_whitelist', type_='foreignkey')
    op.drop_constraint(None, 'radio_ttsvoice', type_='foreignkey')
    op.drop_constraint(None, 'radio_stationlanguage', type_='foreignkey')
    op.drop_constraint(None, 'radio_stationlanguage', type_='foreignkey')
    op.drop_constraint(None, 'radio_stationevent', type_='foreignkey')
    op.drop_constraint(None, 'radio_stationanalytic', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='foreignkey')
    op.drop_constraint(None, 'radio_station', type_='unique')
    op.alter_column('radio_station', 'last_accessed_mobile',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'radio_scheduledprogram', type_='foreignkey')
    op.drop_constraint(None, 'radio_scheduledprogram', type_='foreignkey')
    op.drop_constraint(None, 'radio_scheduledblock', type_='foreignkey')
    op.drop_constraint(None, 'radio_role', type_='foreignkey')
    op.drop_constraint(None, 'radio_role', type_='foreignkey')
    op.drop_constraint(None, 'radio_programnetwork', type_='foreignkey')
    op.drop_constraint(None, 'radio_programnetwork', type_='foreignkey')
    op.drop_constraint(None, 'radio_program', type_='foreignkey')
    op.drop_constraint(None, 'radio_program', type_='foreignkey')
    op.drop_constraint(None, 'radio_personnetwork', type_='foreignkey')
    op.drop_constraint(None, 'radio_personnetwork', type_='foreignkey')
    op.drop_constraint(None, 'radio_personlanguage', type_='foreignkey')
    op.drop_constraint(None, 'radio_personlanguage', type_='foreignkey')
    op.drop_constraint(None, 'radio_person', type_='foreignkey')
    op.drop_constraint(None, 'radio_outgoinggateway', type_='foreignkey')
    op.drop_constraint(None, 'radio_networkusers', type_='foreignkey')
    op.drop_constraint(None, 'radio_networkpadding', type_='foreignkey')
    op.drop_constraint(None, 'radio_incominggateway', type_='foreignkey')
    op.drop_constraint(None, 'radio_episode', type_='foreignkey')
    op.drop_constraint(None, 'onair_program', type_='foreignkey')
    op.drop_constraint(None, 'content_uploads', type_='foreignkey')
    op.drop_constraint(None, 'content_uploads', type_='foreignkey')
    op.drop_constraint(None, 'content_tracknetwork', type_='foreignkey')
    op.drop_constraint(None, 'content_tracknetwork', type_='foreignkey')
    op.drop_constraint(None, 'content_track', type_='foreignkey')
    op.drop_constraint(None, 'content_podcastdownload', type_='foreignkey')
    op.drop_constraint(None, 'content_musicplaylistitem', type_='foreignkey')
    op.drop_constraint(None, 'content_musicplaylistitem', type_='foreignkey')
    op.drop_constraint(None, 'content_musicplaylist', type_='foreignkey')
    op.drop_constraint(None, 'content_musicartist', type_='foreignkey')
    op.drop_constraint(None, 'content_musicalbum', type_='foreignkey')
    op.drop_constraint(None, 'content_music_musicartist', type_='foreignkey')
    op.drop_constraint(None, 'content_music_musicartist', type_='foreignkey')
    op.drop_constraint(None, 'content_music', type_='foreignkey')
    op.drop_constraint(None, 'content_music', type_='foreignkey')
    op.drop_constraint(None, 'content_music', type_='foreignkey')
    op.drop_constraint(None, 'content_communitymenu', type_='foreignkey')
    op.drop_constraint(None, 'content_communitycontent', type_='foreignkey')
    op.drop_constraint(None, 'configuration_voiceprompt', type_='foreignkey')
    ### end Alembic commands ###
