"""extnd_music_ttl_len

Revision ID: 26eb16c4aeaf
Revises: 447d72a67cb0
Create Date: 2017-05-17 21:32:22.146384

"""

# revision identifiers, used by Alembic.
revision = '26eb16c4aeaf'
down_revision = '447d72a67cb0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_music', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_music', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    ### end Alembic commands ###
