"""change_program

Revision ID: 274209eba132
Revises: 23999ea09423
Create Date: 2016-08-23 15:54:39.781511

"""

# revision identifiers, used by Alembic.
revision = '274209eba132'
down_revision = '23999ea09423'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_program', sa.Column('structure', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_program', 'structure')
    ### end Alembic commands ###
