"""duration field required

Revision ID: 27f44f2c66e0
Revises: fff564ee60b
Create Date: 2019-08-02 16:50:19.926775

"""

# revision identifiers, used by Alembic.
revision = '27f44f2c66e0'
down_revision = 'fff564ee60b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
