"""Add jingle interval

Revision ID: 283afd3c9a32
Revises: 53954e77cafc
Create Date: 2019-06-26 12:48:16.180224

"""

# revision identifiers, used by Alembic.
revision = '283afd3c9a32'
down_revision = '53954e77cafc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('jingle_interval', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'jingle_interval')
    ### end Alembic commands ###
