"""editing content tables

Revision ID: 285ff6ea690b
Revises: 477fc699a57e
Create Date: 2016-09-28 16:29:09.664271

"""

# revision identifiers, used by Alembic.
revision = '285ff6ea690b'
down_revision = '477fc699a57e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'content_type',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'radio_contenttype')
    op.add_column(u'content_uploads', sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column(u'content_uploads', sa.Column('track_id', sa.Integer(), nullable=True))
    op.add_column(u'content_uploads', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_column(u'content_uploads', u'expiration_date')
    op.drop_column(u'content_uploads', u'content_contenttypeid')
    op.drop_column(u'content_uploads', u'contenttrack_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_uploads', sa.Column(u'contenttrack_id', sa.INTEGER(), nullable=True))
    op.add_column(u'content_uploads', sa.Column(u'content_contenttypeid', sa.INTEGER(), nullable=True))
    op.add_column(u'content_uploads', sa.Column(u'expiration_date', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column(u'content_uploads', 'type_id')
    op.drop_column(u'content_uploads', 'track_id')
    op.drop_column(u'content_uploads', 'expiry_date')
    op.create_table(u'radio_contenttype',
    sa.Column(u'created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column(u'updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('radio_contenttype_id_seq'::regclass)", nullable=False),
    sa.Column(u'name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column(u'description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint(u'id', name=u'radio_contenttype_pkey')
    )
    op.drop_table(u'content_type')
    ### end Alembic commands ###
