"""prg_add_networkid

Revision ID: 293edef43cf6
Revises: 1f9eed32fdc0
Create Date: 2018-10-11 18:16:22.325758

"""

# revision identifiers, used by Alembic.
revision = '293edef43cf6'
down_revision = '1f9eed32fdc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_programnetwork',
    sa.Column(u'network_id', sa.Integer(), nullable=True),
    sa.Column(u'program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['radio_program.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'radio_programnetwork')
    ### end Alembic commands ###
