"""change_content_uploads

Revision ID: 2a96ee2970e3
Revises: 55a83298ab91
Create Date: 2016-09-12 15:19:19.688744

"""

# revision identifiers, used by Alembic.
revision = '2a96ee2970e3'
down_revision = '55a83298ab91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_uploads', sa.Column('content_contenttypeid', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_uploads', 'content_contenttypeid')
    ### end Alembic commands ###
