"""introducing_hosts

Revision ID: 2b191eb9d05c
Revises: d08fb6070d8
Create Date: 2016-10-31 13:36:51.234391

"""

# revision identifiers, used by Alembic.
revision = '2b191eb9d05c'
down_revision = 'd08fb6070d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('middlename', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('additionalcontact', sa.String(length=100), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('gender_code', sa.Integer(), nullable=True),
    sa.Column('privacy_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['telephony_phonenumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_hostlanguage',
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['radio_host.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['radio_language.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radio_hostlanguage')
    op.drop_table('radio_host')
    ### end Alembic commands ###
