"""accomodating_unicode

Revision ID: 2b6d9d4d6811
Revises: 1bc97024824b
Create Date: 2017-08-22 23:51:36.871626

"""

# revision identifiers, used by Alembic.
revision = '2b6d9d4d6811'
down_revision = '1bc97024824b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'content_music', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300, convert_unicode=True),
               existing_nullable=True)
    op.alter_column(u'content_musicalbum', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255, convert_unicode=True),
               existing_nullable=True)
    op.alter_column(u'content_musicartist', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255, convert_unicode=True),
               existing_nullable=True)
    op.alter_column(u'content_podcastdownload', 'file_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255, convert_unicode=True),
               existing_nullable=True)
    op.alter_column(u'content_podcastdownload', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255, convert_unicode=True),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'content_podcastdownload', 'title',
               existing_type=sa.String(length=255, convert_unicode=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column(u'content_podcastdownload', 'file_name',
               existing_type=sa.String(length=255, convert_unicode=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column(u'content_musicartist', 'title',
               existing_type=sa.String(length=255, convert_unicode=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column(u'content_musicalbum', 'title',
               existing_type=sa.String(length=255, convert_unicode=True),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column(u'content_music', 'title',
               existing_type=sa.String(length=300, convert_unicode=True),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    ### end Alembic commands ###
