"""remove media expiration

Revision ID: 2d0a71aa0f59
Revises: 3464e4fa8884
Create Date: 2019-01-30 09:54:08.157636

"""

# revision identifiers, used by Alembic.
revision = '2d0a71aa0f59'
down_revision = '3464e4fa8884'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_uploads', 'expiry_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_uploads', sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), nullable=True))
    ### end Alembic commands ###
