"""podcast_add_summary_str

Revision ID: 2d17846830ad
Revises: 55bf0671d7ed
Create Date: 2016-11-14 20:22:03.331909

"""

# revision identifiers, used by Alembic.
revision = '2d17846830ad'
down_revision = '55bf0671d7ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column('summary', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_podcastdownload', 'summary')
    ### end Alembic commands ###
