"""strict_sched

Revision ID: 2ffbd3369445
Revises: 0aa1ff595a9f
Create Date: 2020-06-01 20:51:52.916656

"""

# revision identifiers, used by Alembic.
revision = '2ffbd3369445'
down_revision = '0aa1ff595a9f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ##
    op.add_column('radio_station', sa.Column('strict_scheduling', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'strict_scheduling')

    ### end Alembic commands ###
