"""add_deleted_pllistitm

Revision ID: 309c2255ee7d
Revises: 41dfaf78f90b
Create Date: 2016-11-29 13:23:59.859359

"""

# revision identifiers, used by Alembic.
revision = '309c2255ee7d'
down_revision = '41dfaf78f90b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylistitem', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_musicplaylistitem', 'deleted')
    ### end Alembic commands ###
