"""added_community_cnt_tbl

Revision ID: 31c99a16e55c
Revises: 523c59eb774a
Create Date: 2016-11-02 16:13:38.512815

"""

# revision identifiers, used by Alembic.
revision = '31c99a16e55c'
down_revision = '523c59eb774a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_communitycontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('originator', sa.String(length=20), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type_code', sa.Integer(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_communitycontent')
    ### end Alembic commands ###
