"""tts_for_ivr

Revision ID: 31ff8f016d59
Revises: 8d9ab22e533
Create Date: 2019-03-20 19:38:00.630767

"""

# revision identifiers, used by Alembic.
revision = '31ff8f016d59'
down_revision = '8d9ab22e533'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_communitymenu', sa.Column('days_prompt_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('finalization_prompt_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('goodbye_message_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('message_type_prompt_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('no_input_message_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('record_prompt_txt', sa.Text(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('use_tts', sa.Boolean(), nullable=True))
    op.add_column('content_communitymenu', sa.Column('welcome_message_txt', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_communitymenu', 'welcome_message_txt')
    op.drop_column('content_communitymenu', 'use_tts')
    op.drop_column('content_communitymenu', 'record_prompt_txt')
    op.drop_column('content_communitymenu', 'no_input_message_txt')
    op.drop_column('content_communitymenu', 'message_type_prompt_txt')
    op.drop_column('content_communitymenu', 'goodbye_message_txt')
    op.drop_column('content_communitymenu', 'finalization_prompt_txt')
    op.drop_column('content_communitymenu', 'days_prompt_txt')
    ### end Alembic commands ###
