"""add station api key

Revision ID: 324a55db64ea
Revises: dc611df9442
Create Date: 2013-10-26 13:31:23.033088

"""

# revision identifiers, used by Alembic.
revision = '324a55db64ea'
down_revision = 'dc611df9442'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('api_key', sa.String(length=100), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'api_key')
    ### end Alembic commands ###
