"""fix_nm_cnt_tb

Revision ID: 3276b21cf098
Revises: 9622e420e8d
Create Date: 2017-08-23 17:00:14.176182

"""

# revision identifiers, used by Alembic.
revision = '3276b21cf098'
down_revision = '9622e420e8d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcast', sa.Column('date_created', sa.DateTime(timezone=True), server_default='now()', nullable=True))
    op.drop_column(u'content_podcast', u'date_published')
    op.add_column(u'content_podcastdownload', sa.Column('date_published', sa.DateTime(timezone=True), nullable=True))
    op.drop_column(u'content_podcastdownload', u'date_created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column(u'date_created', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column(u'content_podcastdownload', 'date_published')
    op.add_column(u'content_podcast', sa.Column(u'date_published', postgresql.TIMESTAMP(timezone=True), server_default="2017-08-23 16:53:17.97893+00'::timestamp with time zone", nullable=True))
    op.drop_column(u'content_podcast', 'date_created')
    ### end Alembic commands ###
