"""ProgType_pho_funcs

Revision ID: 33313179882b
Revises: 4d9ef0d36ad8
Create Date: 2014-04-29 22:18:51.373724

"""

# revision identifiers, used by Alembic.
revision = '33313179882b'
down_revision = '4d9ef0d36ad8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_programtype', sa.Column('phone_functions', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_programtype', 'phone_functions')
    ### end Alembic commands ###
