"""link_person_to_network

Revision ID: 3639bac661c0
Revises: 1e09e4b69a8c
Create Date: 2016-10-31 12:48:39.355989

"""

# revision identifiers, used by Alembic.
revision = '3639bac661c0'
down_revision = '1e09e4b69a8c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_programtype', 'definition',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('radio_programtype', 'phone_functions',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_programtype', 'phone_functions',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('radio_programtype', 'definition',
               existing_type=sa.TEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    ### end Alembic commands ###
