"""adding_station_roles

Revision ID: 366cffa98fd4
Revises: 54176dfaa1f4
Create Date: 2016-09-22 20:17:32.596822

"""

# revision identifiers, used by Alembic.
revision = '366cffa98fd4'
down_revision = '54176dfaa1f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ##
    op.drop_column('radio_program', u'content_type_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_program', sa.Column(u'content_type_id', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
