"""Link streams and podcasts to networks

Revision ID: 37a2eb86a8df
Revises: fff564ee60b
Create Date: 2019-08-01 22:10:37.892468

"""

# revision identifiers, used by Alembic.
revision = '37a2eb86a8df'
down_revision = 'fff564ee60b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_podcastnetwork',
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['podcast_id'], ['content_podcast.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('content_streamnetwork',
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['content_stream.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_streamnetwork')
    op.drop_table('content_podcastnetwork')
    ### end Alembic commands ###
