"""intro_streams

Revision ID: 37a982c824d0
Revises: 5397ebf3e5e2
Create Date: 2017-08-24 16:14:27.884491

"""

# revision identifiers, used by Alembic.
revision = '37a982c824d0'
down_revision = '5397ebf3e5e2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import func

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'content_stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=func.now(),nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('uri', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('ok_to_play', sa.Boolean(), nullable=True, default=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'content_stream')
    ### end Alembic commands ###
