"""whitelist

Revision ID: 37b19b31785d
Revises: 3c06b874a4d
Create Date: 2016-08-22 15:54:55.881654

"""

# revision identifiers, used by Alembic.
revision = '37b19b31785d'
down_revision = '3c06b874a4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_whitelist',
    sa.Column(u'phone_id', sa.Integer(), nullable=True),
    sa.Column(u'station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['telephony_phonenumber.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'radio_whitelist')
    ### end Alembic commands ###
