"""change_analitics

Revision ID: 3c06b874a4d
Revises: 54068667be18
Create Date: 2016-08-19 16:19:21.884289

"""

# revision identifiers, used by Alembic.
revision = '3c06b874a4d'
down_revision = '54068667be18'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_stationanalytic', sa.Column('record_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('radio_stationanalytic', sa.Column('wifi_connectivity', sa.Float(), nullable=True))
    op.drop_column('radio_stationanalytic', u'wifi_connected')
    op.drop_column('radio_stationanalytic', u'headphone_plug')
    op.alter_column('radio_stationanalytic', 'battery_level',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('radio_stationanalytic', 'gsm_signal',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_stationanalytic', 'gsm_signal',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('radio_stationanalytic', 'battery_level',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.add_column('radio_stationanalytic', sa.Column(u'headphone_plug', sa.BOOLEAN(), nullable=True))
    op.add_column('radio_stationanalytic', sa.Column(u'wifi_connected', sa.BOOLEAN(), nullable=True))
    op.drop_column('radio_stationanalytic', 'wifi_connectivity')
    op.drop_column('radio_stationanalytic', 'record_date')
    ### end Alembic commands ###
