"""add_descr_playlist

Revision ID: 3f5410820abe
Revises: 8d35dbe5bc
Create Date: 2016-11-25 17:06:49.284999

"""

# revision identifiers, used by Alembic.
revision = '3f5410820abe'
down_revision = '8d35dbe5bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylistitemtype', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_musicplaylistitemtype', 'description')
    ### end Alembic commands ###
