"""add station fk to event

Revision ID: 44601d05789b
Revises: 269008ea89b6
Create Date: 2019-04-04 10:47:16.153112

"""

# revision identifiers, used by Alembic.
revision = '44601d05789b'
down_revision = '269008ea89b6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_stationevent', sa.Column('station_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_stationevent', 'station_id')
    ### end Alembic commands ###
