"""direct_relation_music_artist

Revision ID: 447d72a67cb0
Revises: 5121cc7fa2c1
Create Date: 2016-12-02 19:53:24.777467

"""

# revision identifiers, used by Alembic.
revision = '447d72a67cb0'
down_revision = '5121cc7fa2c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_music', sa.Column('artist_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_music', 'artist_id')
    ### end Alembic commands ###
