"""add_dates_playlistitem

Revision ID: 46e8e17edc06
Revises: 32d7e2a6c41c
Create Date: 2016-11-29 01:45:27.196283

"""

# revision identifiers, used by Alembic.
revision = '46e8e17edc06'
down_revision = '32d7e2a6c41c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylistitem', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('content_musicplaylistitem', sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('content_musicplaylistitem', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('content_musicplaylistitem', sa.Column('updated_at', sa.DateTime(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_musicplaylistitem', 'updated_at')
    op.drop_column('content_musicplaylistitem', 'id')
    op.drop_column('content_musicplaylistitem', 'date_created')
    op.drop_column('content_musicplaylistitem', 'created_at')
    ### end Alembic commands ###
