"""add_content_type

Revision ID: 47639c53cc4e
Revises: 1a50a1e1fa9f
Create Date: 2016-08-30 15:04:50.735584

"""

# revision identifiers, used by Alembic.
revision = '47639c53cc4e'
down_revision = '1a50a1e1fa9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_contenttype',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'radio_contenttype')
    ### end Alembic commands ###
