"""call_prg_id

Revision ID: 4c1ec907fb88
Revises: 4b7a79f7ee78
Create Date: 2018-10-24 17:02:03.731247

"""

# revision identifiers, used by Alembic.
revision = '4c1ec907fb88'
down_revision = '4b7a79f7ee78'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
