"""cfg_email_notif

Revision ID: 4c20ef57d701
Revises: 44601d05789b
Create Date: 2019-04-12 13:51:41.776613

"""

# revision identifiers, used by Alembic.
revision = '4c20ef57d701'
down_revision = '44601d05789b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('receive_station_notifications', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'receive_station_notifications')
    ### end Alembic commands ###
