"""drop_unq_constrnt_user_name

Revision ID: 4ca542fb1846
Revises: 18e187ffe893
Create Date: 2016-09-23 18:46:49.387874

"""

# revision identifiers, used by Alembic.
revision = '4ca542fb1846'
down_revision = '18e187ffe893'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
