"""add timezone to each station

Revision ID: 4d0be367f095
Revises: 276473e97ac
Create Date: 2014-03-19 16:43:00.326820

"""

# revision identifiers, used by Alembic.
revision = '4d0be367f095'
down_revision = '276473e97ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('timezone', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'timezone')
    ### end Alembic commands ###
