"""added gateway name

Revision ID: 4d15178b2ddf
Revises: 4d0be367f095
Create Date: 2014-04-26 14:34:01.574475

"""

# revision identifiers, used by Alembic.
revision = '4d15178b2ddf'
down_revision = '4d0be367f095'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'telephony_gateway', sa.Column('name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'telephony_gateway', 'name')
    ### end Alembic commands ###
