"""add deleted bool to things

Revision ID: 4d8d18f311aa
Revises: 4e34b4290fbc
Create Date: 2019-02-27 21:31:09.575521

"""

# revision identifiers, used by Alembic.
revision = '4d8d18f311aa'
down_revision = '4e34b4290fbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylist', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('content_podcast', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('content_stream', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('content_track', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('radio_person', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('radio_program', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_program', 'deleted')
    op.drop_column('radio_person', 'deleted')
    op.drop_column('content_track', 'deleted')
    op.drop_column('content_stream', 'deleted')
    op.drop_column('content_podcast', 'deleted')
    op.drop_column('content_musicplaylist', 'deleted')
    ### end Alembic commands ###
