"""add network name and connected bool for the two sims

Revision ID: 4e34b4290fbc
Revises: 25b2974c7078
Create Date: 2019-02-17 23:23:04.940340

"""

# revision identifiers, used by Alembic.
revision = '4e34b4290fbc'
down_revision = '25b2974c7078'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_stationanalytic', sa.Column('gsm_network_connected_1', sa.Boolean(), nullable=True))
    op.add_column('radio_stationanalytic', sa.Column('gsm_network_connected_2', sa.Boolean(), nullable=True))
    op.add_column('radio_stationanalytic', sa.Column('gsm_network_name_1', sa.String(length=30), nullable=True))
    op.add_column('radio_stationanalytic', sa.Column('gsm_network_name_2', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_stationanalytic', 'gsm_network_name_2')
    op.drop_column('radio_stationanalytic', 'gsm_network_name_1')
    op.drop_column('radio_stationanalytic', 'gsm_network_connected_2')
    op.drop_column('radio_stationanalytic', 'gsm_network_connected_1')
    ### end Alembic commands ###
