"""Add `audio_volume` property to station

Revision ID: 50b58d5a1a3c
Revises: 4c1ec907fb88
Create Date: 2018-12-09 23:55:45.995092

"""

# revision identifiers, used by Alembic.
revision = '50b58d5a1a3c'
down_revision = '4c1ec907fb88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('audio_volume', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'audio_volume')
    ### end Alembic commands ###
