"""link_community_menu_stn

Revision ID: 523c59eb774a
Revises: 56959bc21530
Create Date: 2016-11-02 13:55:25.465168

"""

# revision identifiers, used by Alembic.
revision = '523c59eb774a'
down_revision = '56959bc21530'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_communitymenu', sa.Column('station_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_communitymenu', 'station_id')
    ### end Alembic commands ###
