"""media_amp_factor

Revision ID: 528f90a47515
Revises: 3ec6447ec908
Create Date: 2019-01-01 14:46:56.231800

"""

# revision identifiers, used by Alembic.
revision = '528f90a47515'
down_revision = '3ec6447ec908'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('media_amplification_factor', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'media_amplification_factor')
    ### end Alembic commands ###
