"""add continuous play to tracks

Revision ID: 53954e77cafc
Revises: 2413c9f0671f
Create Date: 2019-05-22 18:27:02.127513

"""

# revision identifiers, used by Alembic.
revision = '53954e77cafc'
down_revision = '2413c9f0671f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_track', sa.Column('continuous_play', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_track', 'continuous_play')
    ### end Alembic commands ###
