"""fix_nm_cnt_tb

Revision ID: 5397ebf3e5e2
Revises: 3276b21cf098
Create Date: 2017-08-23 17:05:53.301160

"""

# revision identifiers, used by Alembic.
revision = '5397ebf3e5e2'
down_revision = '3276b21cf098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column('date_created', sa.DateTime(timezone=True), server_default='now()', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_podcastdownload', 'date_created')
    ### end Alembic commands ###
