"""Trying to add gateway string

Revision ID: 539ec9a1bc41
Revises: 276473e97ac
Create Date: 2014-03-15 20:49:08.099411

"""

# revision identifiers, used by Alembic.
revision = '539ec9a1bc41'
down_revision = '276473e97ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telephony_gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_top', sa.Integer(), nullable=True),
    sa.Column('number_bottom', sa.Integer(), nullable=True),
    sa.Column('sofia_string', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'radio_program', 'duration',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.add_column(u'radio_station', sa.Column('gateway_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'radio_station', 'gateway_id')
    op.alter_column(u'radio_program', 'duration',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.drop_table('telephony_gateway')
    ### end Alembic commands ###
