"""introduce network users

Revision ID: 571474b47435
Revises: 366cffa98fd4
Create Date: 2016-09-22 22:59:06.131443

"""

# revision identifiers, used by Alembic.
revision = '571474b47435'
down_revision = '366cffa98fd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_networkusers',
    sa.Column(u'user_id', sa.Integer(), nullable=True),
    sa.Column(u'network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.drop_table(u'radio_networkadmins')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_networkadmins',
    sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'network_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['network_id'], [u'radio_network.id'], name=u'radio_networkadmins_network_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user_user.id'], name=u'radio_networkadmins_user_id_fkey'),
    sa.PrimaryKeyConstraint()
    )
    op.drop_table(u'radio_networkusers')
    ### end Alembic commands ###
