"""station analytic add createtime

Revision ID: 57cff29eadbf
Revises: 3aeaa37761ae
Create Date: 2013-10-26 17:04:15.119565

"""

# revision identifiers, used by Alembic.
revision = '57cff29eadbf'
down_revision = '3aeaa37761ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_stationanalytics', sa.Column('created_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'created_time')
    ### end Alembic commands ###