"""station analytic add createtime

Revision ID: 57cff29eadbf
Revises: 3aeaa37761ae
Create Date: 2013-10-26 17:04:15.119565

"""

# revision identifiers, used by Alembic.
revision = '57cff29eadbf'
down_revision = '3aeaa37761ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_stationanalytic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('cpu_load', sa.Float(), nullable=True),
    sa.Column('memory_utilization', sa.Float(), nullable=True),
    sa.Column('storage_usage', sa.Float(), nullable=True),
    sa.Column('gsm_connectivity', sa.Float(), nullable=True),
    sa.Column('headphone_plug', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'radio_blockedprogram')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_blockedprogram',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'station_id', sa.INTEGER(), nullable=True),
    sa.Column(u'program_id', sa.INTEGER(), nullable=True),
    sa.Column(u'block_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], [u'radio_scheduledblock.id'], ),
    sa.ForeignKeyConstraint(['program_id'], [u'radio_program.id'], ),
    sa.ForeignKeyConstraint(['station_id'], [u'radio_station.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.drop_table('radio_stationanalytic')
    ### end Alembic commands ###
