"""Added initial tables

Revision ID: 57f461d001ec
Revises: None
Create Date: 2013-10-25 16:52:12.150570

"""

# revision identifiers, used by Alembic.
revision = '57f461d001ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'radio_language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('iso639_1', sa.String(length=2), nullable=True),
    sa.Column('iso639_2', sa.String(length=3), nullable=True),
    sa.Column('locale_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=160), nullable=True),
    sa.Column('local_file', sa.FileField(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=100), nullable=True),
    sa.Column('gender_code', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'telephony_phonenumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('countrycode', sa.String(length=3), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('raw_number', sa.String(length=20), nullable=False),
    sa.Column('number_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_programtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('modifieddate', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('addressline1', sa.String(length=100), nullable=True),
    sa.Column('addressline2', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=True),
    sa.Column('activation_key', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('role_code', sa.SmallInteger(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('user_detail_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_detail_id'], ['user_details.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('radio_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=8), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('middlename', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('additionalcontact', sa.String(length=100), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.Column('gender_code', sa.Integer(), nullable=True),
    sa.Column('privacy_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['telephony_phonenumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('update_recurrence', sa.Text(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('program_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['radio_language.id'], ),
    sa.ForeignKeyConstraint(['program_type_id'], ['radio_programtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('cloud_phone_id', sa.Integer(), nullable=True),
    sa.Column('transmitter_phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_phone_id'], ['telephony_phonenumber.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['radio_location.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user_user.id'], ),
    sa.ForeignKeyConstraint(['transmitter_phone_id'], ['telephony_phonenumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_networkadmins',
    sa.Column(u'user_id', sa.Integer(), nullable=True),
    sa.Column(u'network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table(u'radio_personlanguage',
    sa.Column(u'language_id', sa.Integer(), nullable=True),
    sa.Column(u'person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['radio_language.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['radio_person.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('radio_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['radio_program.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['radio_recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_scheduledepisode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['radio_episode.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_scheduledblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('recurrence', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['radio_person.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_stationlanguage',
    sa.Column(u'language_id', sa.Integer(), nullable=True),
    sa.Column(u'station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['radio_language.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table('onair_episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('scheduledepisode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scheduledepisode_id'], ['radio_scheduledepisode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_paddingcontent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['radio_scheduledblock.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['radio_recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_blockedprogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['radio_scheduledblock.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['radio_program.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'radio_networkpadding',
    sa.Column(u'network_id', sa.Integer(), nullable=True),
    sa.Column(u'paddingcontent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['paddingcontent_id'], ['radio_paddingcontent.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.create_table(u'telephony_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_uuid', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('from_phonenumber_id', sa.Integer(), nullable=True),
    sa.Column('to_phonenumber_id', sa.Integer(), nullable=True),
    sa.Column('a_leg_uuid', sa.String(length=100), nullable=True),
    sa.Column('a_leg_request_uuid', sa.String(length=100), nullable=True),
    sa.Column('onairepisode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_phonenumber_id'], ['telephony_phonenumber.id'], ),
    sa.ForeignKeyConstraint(['onairepisode_id'], ['onair_episode.id'], ),
    sa.ForeignKeyConstraint(['to_phonenumber_id'], ['telephony_phonenumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table(u'telephony_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_uuid', sa.String(length=100), nullable=True),
    sa.Column('sendtime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(length=160), nullable=True),
    sa.Column('from_phonenumber_id', sa.Integer(), nullable=True),
    sa.Column('to_phonenumber_id', sa.Integer(), nullable=True),
    sa.Column('onairepisode_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_phonenumber_id'], ['telephony_phonenumber.id'], ),
    sa.ForeignKeyConstraint(['onairepisode_id'], ['onair_episode.id'], ),
    sa.ForeignKeyConstraint(['to_phonenumber_id'], ['telephony_phonenumber.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'telephony_message')
    op.drop_table(u'telephony_call')
    op.drop_table(u'radio_networkpadding')
    op.drop_table('radio_blockedprogram')
    op.drop_table('radio_paddingcontent')
    op.drop_table('onair_episode')
    op.drop_table(u'radio_stationlanguage')
    op.drop_table(u'radio_role')
    op.drop_table('radio_scheduledblock')
    op.drop_table('radio_scheduledepisode')
    op.drop_table('radio_episode')
    op.drop_table(u'radio_personlanguage')
    op.drop_table(u'radio_networkadmins')
    op.drop_table('radio_station')
    op.drop_table('radio_program')
    op.drop_table('radio_person')
    op.drop_table('user_user')
    op.drop_table(u'radio_location')
    op.drop_table(u'radio_programtype')
    op.drop_table(u'telephony_phonenumber')
    op.drop_table('user_details')
    op.drop_table('radio_recording')
    op.drop_table('radio_network')
    op.drop_table(u'radio_language')
    ### end Alembic commands ###
