"""adding_network_to_person

Revision ID: 58dfdfe8ae74
Revises: 35ced00df34d
Create Date: 2016-10-31 14:08:02.221363

"""

# revision identifiers, used by Alembic.
revision = '58dfdfe8ae74'
down_revision = '35ced00df34d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_person', sa.Column('network_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_person', 'network_id')
    ### end Alembic commands ###
