"""Add voice prompts

Revision ID: 591720fcad12
Revises: 1493003084e8
Create Date: 2019-07-19 10:27:48.371512

"""

# revision identifiers, used by Alembic.
revision = '591720fcad12'
down_revision = '1493003084e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_voiceprompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('on_air', sa.String(length=200), nullable=True),
    sa.Column('on_air_txt', sa.Text(), nullable=True),
    sa.Column('call_end', sa.String(length=200), nullable=True),
    sa.Column('call_end_txt', sa.Text(), nullable=True),
    sa.Column('incoming_call', sa.String(length=200), nullable=True),
    sa.Column('incoming_call_txt', sa.Text(), nullable=True),
    sa.Column('host_welcome', sa.String(length=200), nullable=True),
    sa.Column('host_welcome_txt', sa.Text(), nullable=True),
    sa.Column('host_wait', sa.String(length=200), nullable=True),
    sa.Column('host_wait_txt', sa.Text(), nullable=True),
    sa.Column('wake_mode_activation', sa.String(length=200), nullable=True),
    sa.Column('wake_mode_activation_txt', sa.Text(), nullable=True),
    sa.Column('incoming_reject_activation', sa.String(length=200), nullable=True),
    sa.Column('incoming_reject_activation_txt', sa.Text(), nullable=True),
    sa.Column('incoming_answer_activation', sa.String(length=200), nullable=True),
    sa.Column('incoming_answer_activation_txt', sa.Text(), nullable=True),
    sa.Column('incoming_queue_activation', sa.String(length=200), nullable=True),
    sa.Column('incoming_queue_activation_txt', sa.Text(), nullable=True),
    sa.Column('take_break', sa.String(length=200), nullable=True),
    sa.Column('take_break_txt', sa.Text(), nullable=True),
    sa.Column('input_number', sa.String(length=200), nullable=True),
    sa.Column('input_number_txt', sa.Text(), nullable=True),
    sa.Column('calling_number', sa.String(length=200), nullable=True),
    sa.Column('calling_number_txt', sa.Text(), nullable=True),
    sa.Column('call_queued', sa.String(length=200), nullable=True),
    sa.Column('call_queued_txt', sa.Text(), nullable=True),
    sa.Column('call_failed', sa.String(length=200), nullable=True),
    sa.Column('call_failed_txt', sa.Text(), nullable=True),
    sa.Column('call_back_hangup', sa.String(length=200), nullable=True),
    sa.Column('call_back_hangup_txt', sa.Text(), nullable=True),
    sa.Column('call_back_wait', sa.String(length=200), nullable=True),
    sa.Column('call_back_wait_txt', sa.Text(), nullable=True),
    sa.Column('use_tts', sa.Boolean(), nullable=True),
    sa.Column('prefetch_tts', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['radio_station.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_voiceprompt')
    ### end Alembic commands ###
