"""add networks to tracks

Revision ID: 62b8dd615a3
Revises: 44601d05789b
Create Date: 2019-04-10 10:06:20.086696

"""

# revision identifiers, used by Alembic.
revision = '62b8dd615a3'
down_revision = '44601d05789b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_tracknetwork',
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['radio_network.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['content_track.id'], ),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_tracknetwork')
    ### end Alembic commands ###
