"""deleted_schedule

Revision ID: 6f8ca4801b3
Revises: 274209eba132
Create Date: 2016-08-24 13:13:04.778949

"""

# revision identifiers, used by Alembic.
revision = '6f8ca4801b3'
down_revision = '274209eba132'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_scheduledprogram', sa.Column('deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_scheduledprogram', 'deleted')
    ### end Alembic commands ###
