"""change program status from bool to int

Revision ID: 7ce753c2606
Revises: 1ae1c8228945
Create Date: 2019-09-14 13:12:11.826478

"""

# revision identifiers, used by Alembic.
revision = '7ce753c2606'
down_revision = '1ae1c8228945'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_scheduledprogram', sa.Column('program_status', sa.Integer(), nullable=True))

    # Data migration: takes a few steps...
    # Declare ORM table views. Note that the view contains old and new columns!        
    t = sa.Table(
        'radio_scheduledprogram',
        sa.MetaData(),
        sa.Column('id', sa.String(32)),
        sa.Column('status', sa.Boolean()), # Old column.
        sa.Column('program_status', sa.Integer())
        )
    # Use Alchemy's connection and transaction to noodle over the data.
    connection = op.get_bind()
    # Select all existing names that need migrating.
    results = connection.execute(sa.select([
        t.c.id,
        t.c.status,
        ])).fetchall()
    # Iterate over all selected data tuples.
    for id_, status in results:
        _status = None
        if status is not None:
            _status = 1 if status else 0
        connection.execute(t.update().where(t.c.id == id_).values(
            program_status=_status
            ))

    '''
    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='status::integer')
    '''
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    '''
    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    '''
    ### end Alembic commands ###
