"""change program status from bool to int

Revision ID: 7ce753c2606
Revises: 1ae1c8228945
Create Date: 2019-09-14 13:12:11.826478

"""

# revision identifiers, used by Alembic.
revision = '7ce753c2606'
down_revision = '1ae1c8228945'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_scheduledprogram', 'status',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    ### end Alembic commands ###
