"""tts_config

Revision ID: 8d9ab22e533
Revises: 4d8d18f311aa
Create Date: 2019-03-20 15:02:52.631261

"""

# revision identifiers, used by Alembic.
revision = '8d9ab22e533'
down_revision = '4d8d18f311aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio_ttsaudioformat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_ttssamplerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radio_ttsvoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('gender_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['radio_language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'radio_station', sa.Column('tts_audioformat_id', sa.Integer(), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_samplerate_id', sa.Integer(), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_voice_id', sa.Integer(), nullable=True))
    op.drop_column(u'radio_station', 'tts_sample_rate')
    op.drop_column(u'radio_station', 'tts_gender')
    op.drop_column(u'radio_station', 'tts_audio_format')
    op.drop_column(u'radio_station', 'tts_accent')
    op.drop_column(u'radio_station', 'tts_language_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'radio_station', sa.Column('tts_language_id', sa.INTEGER(), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_accent', sa.VARCHAR(length=100), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_audio_format', sa.VARCHAR(length=100), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_gender', sa.VARCHAR(length=100), nullable=True))
    op.add_column(u'radio_station', sa.Column('tts_sample_rate', sa.VARCHAR(length=100), nullable=True))
    op.drop_column(u'radio_station', 'tts_voice_id')
    op.drop_column(u'radio_station', 'tts_samplerate_id')
    op.drop_column(u'radio_station', 'tts_audioformat_id')
    op.drop_table('radio_ttsvoice')
    op.drop_table('radio_ttssamplerate')
    op.drop_table('radio_ttsaudioformat')
    ### end Alembic commands ###
