"""fix_nm_cnt_tb

Revision ID: 9622e420e8d
Revises: b7867a43c94
Create Date: 2017-08-23 16:52:33.433097

"""

# revision identifiers, used by Alembic.
revision = '9622e420e8d'
down_revision = 'b7867a43c94'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcast', sa.Column('date_published', sa.DateTime(timezone=True), server_default='now()', nullable=True))
    op.drop_column(u'content_podcast', u'date_created')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcast', sa.Column(u'date_created', postgresql.TIMESTAMP(timezone=True), server_default='now()', nullable=True))
    op.drop_column(u'content_podcast', 'date_published')
    ### end Alembic commands ###
