"""Add SIP settings to radio station

Revision ID: be876afb3eb1
Revises: 141d5446a745
Create Date: 2018-09-16 11:48:02.168167

"""

# revision identifiers, used by Alembic.
revision = 'be876afb3eb1'
down_revision = '141d5446a745'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_station', sa.Column('sip_settings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_station', 'sip_settings')
    # ### end Alembic commands ###
