"""introducing_podcasts

Revision ID: cdf3cfea28c
Revises: 31c99a16e55c
Create Date: 2016-11-14 16:41:05.439667

"""

# revision identifiers, used by Alembic.
revision = 'cdf3cfea28c'
down_revision = '31c99a16e55c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_podcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('uri', sa.String(length=200), nullable=True),
    sa.Column('ok_to_play', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_podcastdownload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.String(length=100), nullable=True),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('date_downloaded', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['content_podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_podcastdownload')
    op.drop_table('content_podcast')
    ### end Alembic commands ###
