"""link_host_to_network

Revision ID: d08fb6070d8
Revises: 3639bac661c0
Create Date: 2016-10-31 13:08:02.356226

"""

# revision identifiers, used by Alembic.
revision = 'd08fb6070d8'
down_revision = '3639bac661c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
