"""default_event_freqs

Revision ID: e17e81ece7e2
Revises: a3168ca95801
Create Date: 2020-03-02 13:29:32.854708

"""

# revision identifiers, used by Alembic.
revision = 'e17e81ece7e2'
down_revision = 'a3168ca95801'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', sa.Column('client_update_frequency',
               existing_type=float,
               type_=int,
               default=60))
    op.alter_column('radio_station', sa.Column('analytic_update_frequency',
                    existing_type=float,
                    type_=int,
                    default=30))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('radio_station', sa.Column('client_update_frequency',
                    type_=float))
    op.alter_column('radio_station', sa.Column('analytic_update_frequency',
                    type_=float))
    ### end Alembic commands ###
