"""add_deflt_dlt_pllstitm

Revision ID: f75b5dfaf06
Revises: 2857a895c068
Create Date: 2016-11-29 18:53:47.033901

"""

# revision identifiers, used by Alembic.
revision = 'f75b5dfaf06'
down_revision = '2857a895c068'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_musicplaylistitem', 'deleted')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_musicplaylistitem', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
