"""Split voice prompts

Revision ID: fff564ee60b
Revises: 20bf500febc8
Create Date: 2019-07-30 13:33:01.031653

"""

# revision identifiers, used by Alembic.
revision = 'fff564ee60b'
down_revision = '20bf500febc8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_voiceprompt', sa.Column('call_end_part2', sa.String(length=200), nullable=True))
    op.add_column('configuration_voiceprompt', sa.Column('call_end_part2_txt', sa.Text(), nullable=True))
    op.add_column('configuration_voiceprompt', sa.Column('call_failed_part2', sa.String(length=200), nullable=True))
    op.add_column('configuration_voiceprompt', sa.Column('call_failed_part2_txt', sa.Text(), nullable=True))
    op.add_column('configuration_voiceprompt', sa.Column('call_queued_part2', sa.String(length=200), nullable=True))
    op.add_column('configuration_voiceprompt', sa.Column('call_queued_part2_txt', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration_voiceprompt', 'call_queued_part2_txt')
    op.drop_column('configuration_voiceprompt', 'call_queued_part2')
    op.drop_column('configuration_voiceprompt', 'call_failed_part2_txt')
    op.drop_column('configuration_voiceprompt', 'call_failed_part2')
    op.drop_column('configuration_voiceprompt', 'call_end_part2_txt')
    op.drop_column('configuration_voiceprompt', 'call_end_part2')
    ### end Alembic commands ###
