#!/bin/bash

#This is an example file. you can put this in /etc/init.d or equivalent and run the specified python files as services.

#activate the venv you want to use
source /usr/local/station-telephony/venv/bin/activate

#cd to the station telephony dir, wherever it is
cd /usr/local/station-telephony

#run as a package
python -m sms_server.sms_runner "$1"
