"""call_change

Revision ID: 15d91338011f
Revises: 6f8ca4801b3
Create Date: 2016-08-24 17:30:28.476530

"""

# revision identifiers, used by Alembic.
revision = '15d91338011f'
down_revision = '6f8ca4801b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'telephony_call', sa.Column('from_phonenumber', sa.String(length=20), nullable=True))
    op.add_column(u'telephony_call', sa.Column('to_phonenumber', sa.String(length=20), nullable=True))
    op.drop_column(u'telephony_call', u'from_phonenumber_id')
    op.drop_column(u'telephony_call', u'to_phonenumber_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'telephony_call', sa.Column(u'to_phonenumber_id', sa.INTEGER(), nullable=True))
    op.add_column(u'telephony_call', sa.Column(u'from_phonenumber_id', sa.INTEGER(), nullable=True))
    op.drop_column(u'telephony_call', 'to_phonenumber')
    op.drop_column(u'telephony_call', 'from_phonenumber')
    ### end Alembic commands ###
