"""changing_playlist_items_rep

Revision ID: 1824121342c8
Revises: 52392b489bd1
Create Date: 2016-11-29 01:52:41.947386

"""

# revision identifiers, used by Alembic.
revision = '1824121342c8'
down_revision = '52392b489bd1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_musicplaylistitem')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_musicplaylistitem',
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playlist_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('playlist_item_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], [u'content_musicplaylist.id'], name=u'content_musicplaylistitem_playlist_id_fkey'),
    sa.ForeignKeyConstraint(['playlist_item_type_id'], [u'content_musicplaylistitemtype.id'], name=u'content_musicplaylistitem_playlist_item_type_id_fkey'),
    sa.PrimaryKeyConstraint()
    )
    ### end Alembic commands ###
