"""accomodating_unicode

Revision ID: 1bc97024824b
Revises: ab67c5b937e
Create Date: 2017-08-22 23:46:27.528637

"""

# revision identifiers, used by Alembic.
revision = '1bc97024824b'
down_revision = 'ab67c5b937e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
