"""drop_unq_constrnt_use

Revision ID: 3612eba10920
Revises: 4ca542fb1846
Create Date: 2016-09-23 18:52:18.527648

"""

# revision identifiers, used by Alembic.
revision = '3612eba10920'
down_revision = '4ca542fb1846'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', u'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column(u'name', sa.VARCHAR(length=100), nullable=False))
    ### end Alembic commands ###
