"""chng_default_dt

Revision ID: 39fb951fe296
Revises: 2b6d9d4d6811
Create Date: 2017-08-23 14:13:08.861938

"""

# revision identifiers, used by Alembic.
revision = '39fb951fe296'
down_revision = '2b6d9d4d6811'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
