"""changing_playlist_items_rep

Revision ID: 41dfaf78f90b
Revises: 1824121342c8
Create Date: 2016-11-29 01:57:59.717155

"""

# revision identifiers, used by Alembic.
revision = '41dfaf78f90b'
down_revision = '1824121342c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_musicplaylistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('playlist_item_id', sa.Integer(), nullable=True),
    sa.Column('playlist_item_type_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['content_musicplaylist.id'], ),
    sa.ForeignKeyConstraint(['playlist_item_type_id'], ['content_musicplaylistitemtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_musicplaylistitem')
    ### end Alembic commands ###
