"""chng_default_dt

Revision ID: 43b646fd9f17
Revises: 39fb951fe296
Create Date: 2017-08-23 14:17:09.242528

"""

# revision identifiers, used by Alembic.
revision = '43b646fd9f17'
down_revision = '39fb951fe296'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_podcast', u'date_created')
    op.alter_column(u'content_podcast', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default="2017-01-11 21:14:53.469648+00'::timestamp with time zone")
    op.drop_column(u'content_podcastdownload', u'date_downloaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column(u'date_downloaded', postgresql.TIMESTAMP(timezone=True), server_default="2017-01-11 21:14:53.469648+00'::timestamp with time zone", nullable=True))
    op.alter_column(u'content_podcast', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default="2017-01-11 21:14:53.469648+00'::timestamp with time zone")
    op.add_column(u'content_podcast', sa.Column(u'date_created', postgresql.TIMESTAMP(timezone=True), server_default="2017-01-11 21:14:53.469648+00'::timestamp with time zone", nullable=True))
    ### end Alembic commands ###
