"""drop_readd_user_name

Revision ID: 477fc699a57e
Revises: 3612eba10920
Create Date: 2016-09-23 18:57:48.558292

"""

# revision identifiers, used by Alembic.
revision = '477fc699a57e'
down_revision = '3612eba10920'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('name', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'name')
    ### end Alembic commands ###
