"""re_add_program_type

Revision ID: 5121cc7fa2c1
Revises: 21c434fca60d
Create Date: 2016-11-30 16:00:16.376684

"""

# revision identifiers, used by Alembic.
revision = '5121cc7fa2c1'
down_revision = '21c434fca60d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radio_program', sa.Column('program_type_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_program', 'program_type_id')
    ### end Alembic commands ###
