"""add_dates_playlistitem

Revision ID: 52392b489bd1
Revises: 46e8e17edc06
Create Date: 2016-11-29 01:46:50.109650

"""

# revision identifiers, used by Alembic.
revision = '52392b489bd1'
down_revision = '46e8e17edc06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
