"""add_status_program

Revision ID: 55a83298ab91
Revises: 25c0610f6dbf
Create Date: 2016-09-02 13:44:15.358055

"""

# revision identifiers, used by Alembic.
revision = '55a83298ab91'
down_revision = '25c0610f6dbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_uploads', sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column(u'content_uploads', sa.Column('ok_to_play', sa.Boolean(), nullable=True))
    op.add_column('radio_scheduledprogram', sa.Column('status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radio_scheduledprogram', 'status')
    op.drop_column(u'content_uploads', 'ok_to_play')
    op.drop_column(u'content_uploads', 'expiration_date')
    ### end Alembic commands ###
