"""podcast_drop_summary

Revision ID: 55bf0671d7ed
Revises: 22cc5d6d7fc0
Create Date: 2016-11-14 20:21:18.458431

"""

# revision identifiers, used by Alembic.
revision = '55bf0671d7ed'
down_revision = '22cc5d6d7fc0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_podcastdownload', u'summary')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_podcastdownload', sa.Column(u'summary', sa.VARCHAR(length=100), nullable=True))
    ### end Alembic commands ###
