"""introducing_community_menu

Revision ID: 56959bc21530
Revises: 21a22e8b1948
Create Date: 2016-11-02 13:52:35.057279

"""

# revision identifiers, used by Alembic.
revision = '56959bc21530'
down_revision = '21a22e8b1948'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_communitymenu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('welcome_message', sa.String(length=200), nullable=True),
    sa.Column('no_input_message', sa.String(length=200), nullable=True),
    sa.Column('days_prompt', sa.String(length=200), nullable=True),
    sa.Column('record_prompt', sa.String(length=200), nullable=True),
    sa.Column('message_type_prompt', sa.String(length=200), nullable=True),
    sa.Column('finalization_prompt', sa.String(length=200), nullable=True),
    sa.Column('goodbye_message', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_communitymenu')
    ### end Alembic commands ###
