"""change_uploads2

Revision ID: 592ac1a4ca88
Revises: 9dfe6c16692
Create Date: 2016-08-31 14:29:08.493739

"""

# revision identifiers, used by Alembic.
revision = '592ac1a4ca88'
down_revision = '9dfe6c16692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'content_track', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'content_track', 'uploaded_by')
    ### end Alembic commands ###
